server:
  port: 9999
spring:
  application:
    name: jmz-gateway
  config:
    additional-location: classpath:/
    import:
      - optional:classpath:config.yml
      - optional:nacos:common.yml?group=${NACOS_NAMESPACE:dev}
      - optional:nacos:jmz-gateway-dev.yml
  profiles:
    include: route
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: ${jmz.game-boosting.nacos.server.url}:${jmz.game-boosting.nacos.server.port}
      config:
        namespace: ${NACOS_NAMESPACE:dev}
    gateway:
      globalcors:
        globalCorsConfigurationSource:
          allowedOriginPatterns: "*"
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowedHeaders:
            - "*"
          allowCredentials: true
          maxAge: 3600
    openfeign:
      client:
        config:
          default:
            connect-timeout: 10000
            read-timeout: 30000
      hystrix:
        enabled: true
      compression:
        request:
          enabled: true
        response:
          enabled: true

logging:
  level:
    com.atguigu.business.feign: debug
